/**
 * The complete initial KC inventory: 89 knowledge components with
 * required-for-instruction prerequisite edges, transcribed from
 * docs/adaptive-learning-design.md §1.3 (tables A–E).
 *
 * Facts nodes (MUL.FACT.T1..T10) are parallel, not a ladder.
 * "related" links are undirected metadata and never DAG edges.
 */
import type { KnowledgeGraphNode, SkillId, ThemeId } from './types'

const OA: ThemeId = 'optellen-aftrekken'
const MEAS: ThemeId = 'meten'
const MD: ThemeId = 'vermenigvuldigen-delen'
const TG: ThemeId = 'tijd-geld'

/** Shared foundations live on bridges between islands. */
const ALL_THEMES: ThemeId[] = [OA, MEAS, MD, TG]

function node(
  id: SkillId,
  themes: ThemeId[],
  cluster: string,
  titleNl: string,
  learnerCanNl: string,
  observableCheck: string,
  prerequisites: SkillId[],
  criticalVariationTags: string[],
): KnowledgeGraphNode {
  return { id, themes, cluster, titleNl, learnerCanNl, observableCheck, prerequisites, criticalVariationTags }
}

export const KNOWLEDGE_GRAPH: KnowledgeGraphNode[] = [
  // ---------- A. Shared number sense and problem-solving foundations ----------
  node('FND.COUNT.Group', ALL_THEMES, 'foundations', 'Gelijke groepen tellen',
    'Ik kan gelijke groepen tellen en uitleggen dat hergroeperen de hoeveelheid niet verandert.',
    'Counts equal groups and explains that regrouping preserves the total.',
    [], []),
  node('FND.FACT.AddWithin20', ALL_THEMES, 'foundations', 'Optellen tot 20',
    'Ik kan sommen tot 20 maken, ook over de tien.',
    'Composes sums within 20, including crossing ten.',
    ['FND.COUNT.Group'], ['cross-ten']),
  node('FND.FACT.SubWithin20', ALL_THEMES, 'foundations', 'Aftrekken tot 20',
    'Ik kan verschillen tot 20 uitrekenen, ook over de tien.',
    'Finds a difference within 20, including crossing ten.',
    ['FND.FACT.AddWithin20'], ['cross-ten']),
  node('PV.DHTE.Identify', ALL_THEMES, 'place-value', 'Waarde van cijfers',
    'Ik kan zeggen hoeveel een cijfer waard is (D/H/T/E), niet alleen hoe het heet.',
    'Identifies the value, not just the name, of a digit in D/H/T/E.',
    ['FND.COUNT.Group'], []),
  node('PV.DHTE.Decompose', ALL_THEMES, 'place-value', 'Getallen splitsen',
    'Ik kan 5307 schrijven als 5000 + 300 + 0 + 7 zonder de nul te verliezen.',
    'Expresses 5307 as 5000 + 300 + 0 + 7 without losing zero positions.',
    ['PV.DHTE.Identify'], ['zero-position']),
  node('PV.DHTE.Compose', ALL_THEMES, 'place-value', 'Getallen opbouwen',
    'Ik kan van losse plaatswaarden weer één getal maken.',
    'Reconstructs a numeral from shuffled place-value quantities.',
    ['PV.DHTE.Decompose'], ['zero-position']),
  node('PV.DHTE.Exchange', ALL_THEMES, 'place-value', 'Ruilen tussen plaatsen',
    'Ik kan 1 H ruilen voor 10 T (of 1 T voor 10 E) zonder dat de waarde verandert.',
    'Exchanges 1 H for 10 T or 1 T for 10 E without changing value.',
    ['PV.DHTE.Compose'], []),
  node('PV.SCALE.TenHundred', ALL_THEMES, 'place-value', 'Keer 10 en keer 100',
    'Ik kan uitleggen waarom ×10 en ×100 werken, ook bij nullen in het getal.',
    'Explains ×10/×100 and inverse scaling by unit value, including zero digits.',
    ['PV.DHTE.Exchange'], []),
  node('NUM.LINE.Interval', ALL_THEMES, 'number-line', 'Afstand op de getallenlijn',
    'Ik kan de afstand tussen streepjes afleiden uit twee labels.',
    'Derives a tick interval from two labels and the number of spaces.',
    ['FND.COUNT.Group'], []),
  node('NUM.LINE.Position', ALL_THEMES, 'number-line', 'Getallen op de lijn',
    'Ik kan getallen vinden en aflezen op een getallenlijn met een schaal.',
    'Locates or reads values using an established scale.',
    ['NUM.LINE.Interval', 'PV.DHTE.Compose'], []),
  node('NUM.ROUND.Ten', ALL_THEMES, 'rounding', 'Afronden op tientallen',
    'Ik kan afronden op het dichtstbijzijnde tiental.',
    'Rounds to the nearest ten using neighboring multiples.',
    ['NUM.LINE.Position'], []),
  node('NUM.ROUND.Hundred', ALL_THEMES, 'rounding', 'Afronden op honderdtallen',
    'Ik kan afronden op het dichtstbijzijnde honderdtal, ook bij precies de helft.',
    'Rounds to the nearest hundred, including halfway cases.',
    ['NUM.ROUND.Ten'], ['halfway']),
  node('REL.ADD.Inverse', ALL_THEMES, 'foundations', 'Optellen en aftrekken omgekeerd',
    'Ik weet dat bij a + b = c ook c − a = b hoort.',
    'Connects a + b = c with c − a = b.',
    ['FND.FACT.AddWithin20', 'FND.FACT.SubWithin20'], []),
  node('META.MODEL.Quantity', ALL_THEMES, 'meta', 'Wat weet je? Wat zoek je?',
    'Ik kan in een tekening laten zien welke hoeveelheden ik ken en welke ik zoek.',
    'Identifies known quantities and the unknown in a bar, sketch, or grouping model.',
    ['FND.COUNT.Group'], []),
  node('META.EQUATION.Select', ALL_THEMES, 'meta', 'Welke som hoort erbij?',
    'Ik kan de juiste som kiezen bij een verhaaltje, niet alleen op een zoekwoord.',
    'Matches a quantity relationship to an equation, not a keyword.',
    ['META.MODEL.Quantity', 'REL.ADD.Inverse'], ['two-operation-families']),
  node('META.ANSWER.Unit', ALL_THEMES, 'meta', 'Wat telt je antwoord?',
    'Ik kan zeggen wat mijn antwoord betekent (bijv. euro’s of minuten).',
    'States what the numerical answer counts or measures.',
    ['META.MODEL.Quantity'], []),
  node('META.CHECK.EstimateInverse', ALL_THEMES, 'meta', 'Klopt je antwoord?',
    'Ik kan met schatten of omkeren controleren of mijn antwoord kan kloppen.',
    'Uses an estimate or an inverse relation to test plausibility; explains the check.',
    ['NUM.ROUND.Ten', 'REL.ADD.Inverse', 'META.ANSWER.Unit'], []),

  // ---------- B. Optellen en aftrekken ----------
  node('ADD.JUMP.NoBridge', [OA], 'add-jump', 'Sprongen zonder brug',
    'Ik kan sprongen van honderdtallen, tientallen en eenheden maken zonder brug.',
    'Partitions an addend into H/T/E and accumulates correct endpoints without a bridge.',
    ['PV.DHTE.Decompose', 'NUM.LINE.Position', 'FND.FACT.AddWithin20'], []),
  node('ADD.JUMP.TenBridge', [OA], 'add-jump', 'Over de tien springen',
    'Ik kan over een tienen-grens springen en toch op de goede plek uitkomen.',
    'Crosses a ten boundary while preserving the total jump.',
    ['ADD.JUMP.NoBridge', 'PV.DHTE.Exchange'], ['ten-bridge']),
  node('ADD.JUMP.HundredBridge', [OA], 'add-jump', 'Over de honderd springen',
    'Ik kan over een honderden-grens springen, zoals 547 + 70 = 617.',
    'Crosses a hundred boundary; e.g. 547 + 70 = 617.',
    ['ADD.JUMP.TenBridge'], ['hundred-bridge']),
  node('SUB.JUMP.NoBridge', [OA], 'sub-jump', 'Terugspringen zonder brug',
    'Ik kan in stapjes terugtellen met honderdtallen, tientallen en eenheden.',
    'Subtracts successive place-value parts in the correct direction.',
    ['PV.DHTE.Decompose', 'NUM.LINE.Position', 'FND.FACT.SubWithin20'], []),
  node('SUB.JUMP.TenBridge', [OA], 'sub-jump', 'Terug over de tien',
    'Ik kan over een tienen-grens aftrekken zonder te veel af te trekken.',
    'Subtracts across a ten using an equivalent partition or bridge.',
    ['SUB.JUMP.NoBridge', 'PV.DHTE.Exchange'], ['ten-bridge']),
  node('SUB.JUMP.HundredBridge', [OA], 'sub-jump', 'Terug over de honderd',
    'Ik kan over een honderden-grens aftrekken en controleren waar ik uitkom.',
    'Subtracts across a hundred and checks the endpoint.',
    ['SUB.JUMP.TenBridge'], ['hundred-bridge']),
  node('ADD.COLUMN.Align', [OA], 'columns', 'Onder elkaar optellen',
    'Ik kan H, T en E netjes onder elkaar zetten en optellen zonder te onthouden.',
    'Aligns H/T/E and adds columns without regrouping.',
    ['PV.DHTE.Compose', 'FND.FACT.AddWithin20'], []),
  node('ADD.COLUMN.Carry', [OA], 'columns', 'Onthouden bij optellen',
    'Ik kan tien eenheden ruilen voor één tiental en dat onthouden bij de volgende kolom.',
    'Regroups ten units into the next column, including a chained carry.',
    ['ADD.COLUMN.Align', 'PV.DHTE.Exchange'], ['single-carry', 'chained-carry']),
  node('SUB.COLUMN.Align', [OA], 'columns', 'Onder elkaar aftrekken',
    'Ik kan onder elkaar aftrekken zonder te lenen.',
    'Aligns minuend/subtrahend and subtracts without regrouping.',
    ['PV.DHTE.Compose', 'FND.FACT.SubWithin20'], []),
  node('SUB.COLUMN.BorrowCrossout', [OA], 'columns', 'Lenen bij de buren',
    'Ik kan lenen van de buurkolom en beide kolommen aanpassen.',
    'Exchanges from a nonzero neighboring column and updates both columns.',
    ['SUB.COLUMN.Align', 'PV.DHTE.Exchange'], ['single-borrow']),
  node('SUB.COLUMN.BorrowAcrossZero', [OA], 'columns', 'Lenen over een nul',
    'Ik kan lenen als er een nul tussen staat, zonder de waarde te veranderen.',
    'Regroups across a zero column while conserving the minuend.',
    ['SUB.COLUMN.BorrowCrossout'], ['across-zero']),
  node('REL.ADD.MissingPart', [OA], 'foundations', 'Ontbrekend deel zoeken',
    'Ik kan in een piramide of som het ontbrekende getal vinden en controleren.',
    'Solves a missing addend/part in a pyramid or equation and verifies it.',
    ['REL.ADD.Inverse', 'ADD.JUMP.TenBridge', 'SUB.JUMP.TenBridge'], ['inverse-verification']),

  // ---------- C. Meten ----------
  node('MEAS.UNIT.Select', [MEAS], 'meas-units', 'Welke maat past erbij?',
    'Ik kan een passende maat kiezen voor lengte, gewicht of inhoud.',
    'Chooses a plausible length, mass, or capacity unit for an object.',
    ['META.ANSWER.Unit'], ['length', 'mass', 'capacity']),
  node('MEAS.LENGTH.Anchor', [MEAS], 'meas-length', 'Lengtematen kennen',
    'Ik ken mm, cm, dm, m en km met echte voorbeelden.',
    'Establishes mm/cm/dm/m/km relationships using reference lengths.',
    ['MEAS.UNIT.Select', 'PV.SCALE.TenHundred'], ['m-km-1000']),
  node('MEAS.LENGTH.Convert', [MEAS], 'meas-length', 'Lengte omrekenen',
    'Ik kan lengtes omrekenen met de echte verhouding, ook m naar km.',
    'Converts length by the actual unit ratio, including m↔km.',
    ['MEAS.LENGTH.Anchor'], ['both-directions']),
  node('MEAS.MASS.Anchor', [MEAS], 'meas-mass', 'Gewichtsmaten kennen',
    'Ik ken kg, g en mg, en een halve en kwart kilo.',
    'Establishes kg↔g↔mg and half/quarter-kilogram anchors.',
    ['MEAS.UNIT.Select', 'PV.SCALE.TenHundred'], ['half-kg', 'quarter-kg']),
  node('MEAS.MASS.Convert', [MEAS], 'meas-mass', 'Gewicht omrekenen',
    'Ik kan met keer 1000 omrekenen en hoeveelheden samenstellen.',
    'Converts by 1,000 and combines/splits mass quantities.',
    ['MEAS.MASS.Anchor'], ['both-directions']),
  node('MEAS.CAPACITY.Anchor', [MEAS], 'meas-capacity', 'Inhoudsmaten kennen',
    'Ik ken L, dL, cL en mL, en een halve en kwart liter.',
    'Establishes L/dL/cL/mL, including half and quarter liter.',
    ['MEAS.UNIT.Select', 'PV.SCALE.TenHundred'], ['half-liter', 'quarter-liter']),
  node('MEAS.CAPACITY.Convert', [MEAS], 'meas-capacity', 'Inhoud omrekenen',
    'Ik kan inhoud omrekenen in beide richtingen.',
    'Converts capacity by the actual ratio, in both directions.',
    ['MEAS.CAPACITY.Anchor'], ['both-directions']),
  node('MEAS.MIXED.ComposeSplit', [MEAS], 'meas-units', 'Samenstellen en splitsen',
    'Ik kan 4 m 25 cm schrijven als 425 cm én weer terug.',
    'Converts 4 m 25 cm to 425 cm and inverts the representation.',
    ['MEAS.LENGTH.Convert', 'PV.DHTE.Decompose', 'REL.ADD.Inverse'], []),
  node('MEAS.COMPARE.Normalize', [MEAS], 'meas-units', 'Vergelijken met gelijke maat',
    'Ik zet eerst alles in dezelfde maat voordat ik vergelijk.',
    'Chooses a common unit before comparing differently written quantities.',
    ['MEAS.LENGTH.Convert', 'NUM.LINE.Position'], []),
  node('MEAS.RULER.ZeroStart', [MEAS], 'meas-instruments', 'Lineaal vanaf nul',
    'Ik kan een afstand aflezen vanaf nul, ook in millimeters.',
    'Reads endpoint distance from zero, including millimeter subdivisions.',
    ['NUM.LINE.Position', 'MEAS.LENGTH.Anchor'], ['millimeter']),
  node('MEAS.RULER.Offset', [MEAS], 'meas-instruments', 'Meten met een afstand',
    'Ik begrijp dat lengte = eind − begin, ook als het voorwerp niet bij nul ligt.',
    'Computes end − start; distinguishes position from length.',
    ['MEAS.RULER.ZeroStart', 'SUB.JUMP.TenBridge'], ['offset', 'cropped-ruler']),
  node('MEAS.SCALE.Interval', [MEAS], 'meas-instruments', 'Streepjes op een schaal',
    'Ik kan uitrekenen hoeveel één streepje is bij een maatbeker of weegschaal.',
    'Infers the size of an unlabeled graduation from labeled bounds.',
    ['NUM.LINE.Interval', 'MEAS.UNIT.Select'], []),
  node('MEAS.BEAKER.Read', [MEAS], 'meas-instruments', 'Maatbeker aflezen',
    'Ik kan de vloeistof aflezen met de schaal van de beker.',
    'Reads a level using the beker’s scale, not a memorized picture height.',
    ['MEAS.SCALE.Interval', 'MEAS.CAPACITY.Anchor'], []),
  node('MEAS.MASS.ReadScale', [MEAS], 'meas-instruments', 'Weegschaal aflezen',
    'Ik kan een wijzerplaat of digitale weegschaal aflezen met de juiste maat.',
    'Reads a dial/digital mass scale and supplies its unit.',
    ['MEAS.SCALE.Interval', 'MEAS.MASS.Anchor'], []),
  node('MEAS.CONTEXT.CombineLimit', [MEAS], 'meas-context', 'Meten in verhaaltjes',
    'Ik kan maten omrekenen, bij elkaar optellen en vergelijken met een limiet.',
    'Normalizes, combines quantities, and compares with a recipe or weight limit.',
    ['MEAS.MIXED.ComposeSplit', 'MEAS.COMPARE.Normalize', 'META.EQUATION.Select', 'ADD.JUMP.HundredBridge'], []),

  // ---------- D. Vermenigvuldigen en delen ----------
  node('MUL.GROUP.Array', [MD], 'mul-groups', 'Groepen en rijen',
    'Ik kan gelijke groepen, herhaald optellen en rijen/kolommen met elkaar verbinden.',
    'Connects equal groups, repeated addition, and array rows/columns.',
    ['FND.COUNT.Group', 'FND.FACT.AddWithin20'], []),
  ...([1, 2, 3, 4, 5, 6, 7, 8, 9, 10] as const).map((n) =>
    node(`MUL.FACT.T${n}`, [MD], 'mul-facts', `Tafel van ${n}`,
      `Ik ken de tafel van ${n}, ook als een factor ontbreekt.`,
      `Retrieves/derives the ${n}s facts, including missing-factor questions.`,
      ['MUL.GROUP.Array'],
      [`T${n}:all-multipliers`, 'missing-factor']),
  ),
  node('MUL.SCALE.OneFactor', [MD], 'mul-scale', 'Keer 10 en keer 100 bij vermenigvuldigen',
    'Ik zie dat 4 × 3, 4 × 30 en 4 × 300 bij elkaar horen.',
    'Relates 4 × 3, 4 × 30, and 4 × 300 by value.',
    ['MUL.GROUP.Array', 'PV.SCALE.TenHundred'], []),
  node('MUL.SCALE.TwoFactors', [MD], 'mul-scale', 'Twee factoren groter maken',
    'Ik kan uitleggen waarom 40 × 30 twee keer groter wordt.',
    'Explains the combined scaling in 40 × 30.',
    ['MUL.SCALE.OneFactor'], []),
  node('MUL.SPLIT.Distribute', [MD], 'mul-split', 'Splitsend vermenigvuldigen',
    'Ik kan 7 × 47 uitrekenen als 7 × 40 plus 7 × 7.',
    'Partitions 7 × 47 as 7 × 40 + 7 × 7 and recombines.',
    ['MUL.SCALE.OneFactor', 'ADD.JUMP.HundredBridge'], []),
  node('MUL.COLUMN.PartialProducts', [MD], 'mul-column', 'Tussensommen onder elkaar',
    'Ik kan tussensommen op de goede plek onder elkaar zetten.',
    'Aligns partial products with their place values.',
    ['MUL.SPLIT.Distribute', 'ADD.COLUMN.Align'], []),
  node('MUL.COLUMN.Carry', [MD], 'mul-column', 'Onthouden bij vermenigvuldigen',
    'Ik kan het onthouden van vermenigvuldigen verbinden met de tussensommen.',
    'Relates compressed carrying to the full partial products.',
    ['MUL.COLUMN.PartialProducts', 'ADD.COLUMN.Carry'], []),
  node('DIV.GROUP.EqualShare', [MD], 'div-groups', 'Eerlijk delen',
    'Ik kan zien hoeveel groepen er zijn en hoe groot elke groep is.',
    'Distinguishes number of groups from size of each group.',
    ['MUL.GROUP.Array', 'REL.ADD.Inverse'], []),
  node('DIV.FACT.Inverse', [MD], 'div-facts', 'Delen met de tafel',
    'Ik kan q × d = N gebruiken om te delen of de ontbrekende factor te vinden.',
    'Uses q × d = N to solve exact division and missing-factor questions.',
    ['DIV.GROUP.EqualShare'], []),
  node('DIV.SCALE.CancelFactor', [MD], 'div-scale', 'Delen met nullen',
    'Ik kan uitleggen waarom 1200 ÷ 30 hetzelfde antwoord geeft als 120 ÷ 3.',
    'Explains why scaling both dividend and divisor equally preserves quotient.',
    ['DIV.FACT.Inverse', 'MUL.SCALE.OneFactor'], []),
  node('DIV.REMAINDER.Compute', [MD], 'div-remainder', 'Delen met rest',
    'Ik kan een quotiënt en rest geven waarbij N = q × d + r en r kleiner dan d.',
    'Produces q and r with N = qd + r and 0 ≤ r < d.',
    ['DIV.FACT.Inverse', 'SUB.JUMP.TenBridge'], ['exact', 'non-exact']),
  node('DIV.REMAINDER.CeilContext', [MD], 'div-remainder', 'Rest: nog één erbij',
    'Bij volle bussen of dozen weet ik dat de rest ook mee moet.',
    'Counts enough containers when any leftover requires another one.',
    ['DIV.REMAINDER.Compute', 'META.EQUATION.Select', 'META.ANSWER.Unit'], ['ceil', 'exact-case']),
  node('DIV.REMAINDER.FloorContext', [MD], 'div-remainder', 'Rest: niets extra',
    'Bij geld of materiaal weet ik dat de rest overblijft.',
    'Counts affordable/complete groups without spending or using the remainder.',
    ['DIV.REMAINDER.Compute', 'META.EQUATION.Select', 'META.ANSWER.Unit'], ['floor', 'exact-case']),
  node('DIV.REMAINDER.LeftoverUnit', [MD], 'div-remainder', 'Wat is de rest?',
    'Ik kan zeggen wat de rest betekent in de oorspronkelijke eenheid.',
    'Interprets the remainder in original units and checks its bound.',
    ['DIV.REMAINDER.Compute', 'META.ANSWER.Unit'], []),

  // ---------- E. Tijd en geld ----------
  node('TIME.UNIT.HourMinute', [TG], 'time-units', '1 uur = 60 minuten',
    'Ik weet dat een uur 60 minuten duurt, niet 100.',
    'Treats one hour as 60 minutes, not 100.',
    ['FND.COUNT.Group'], []),
  node('TIME.READ.MinuteFive', [TG], 'time-read', 'Klok per 5 minuten',
    'Ik kan de grote wijzer aflezen per 5 minuten.',
    'Reads the long hand in five-minute groups.',
    ['NUM.LINE.Interval', 'TIME.UNIT.HourMinute'], []),
  node('TIME.READ.HourProgress', [TG], 'time-read', 'Welk uur is voorbij?',
    'Ik zie dat de kleine wijzer meebeweegt en bijna het volgende uur aanwijst.',
    'Reads the short hand between numerals as the hour progresses.',
    ['TIME.READ.MinuteFive'], ['near-hour']),
  node('TIME.READ.Digital24', [TG], 'time-read', 'Digitale klok 24 uur',
    'Ik kan 12-uurs tijden koppelen aan ochtend/middag in 24-uurs notatie.',
    'Connects 12-hour time to morning/afternoon in 24-hour notation.',
    ['TIME.READ.HourProgress'], ['evening']),
  node('TIME.READ.DutchHourQuarter', [TG], 'time-dutch', 'Uur en kwartieren',
    'Ik begrijp "uur", "kwart over" en "kwart voor".',
    'Interprets uur, kwart over, and kwart voor.',
    ['TIME.READ.HourProgress'], ['kwart-over', 'kwart-voor']),
  node('TIME.READ.DutchHourOffset', [TG], 'time-dutch', '5 over en 10 voor',
    'Ik begrijp "5/10 over" het huidige uur en "5/10 voor" het volgende uur.',
    'Interprets 5/10 over the current hour and 5/10 voor the next hour.',
    ['TIME.READ.DutchHourQuarter', 'FND.FACT.SubWithin20'], []),
  node('TIME.READ.DutchHalfNextHour', [TG], 'time-dutch', 'Half betekent: eraan komen',
    'Ik weet dat "half 9" 08:30 betekent.',
    'Interprets half 9 as 08:30 or 20:30 with context.',
    ['TIME.READ.DutchHourQuarter'], ['half', '12-wrap']),
  node('TIME.READ.DutchPhrasingHalfHourOffset', [TG], 'time-dutch', 'Voor en over half',
    'Ik begrijp "5/10 voor half" en "5/10 over half".',
    'Interprets voor/over half around the upcoming named hour.',
    ['TIME.READ.DutchHalfNextHour', 'FND.FACT.SubWithin20'], ['voor-half', 'over-half', '12-wrap']),
  node('TIME.CALC.Offset', [TG], 'time-calc', 'Tijd erbij en eraf',
    'Ik kan 10, 15, 30 of 45 minuten vooruit of terugrekenen, ook over het uur.',
    'Moves ±10/15/30/45 minutes across an hour boundary.',
    ['TIME.READ.Digital24', 'TIME.UNIT.HourMinute', 'ADD.JUMP.TenBridge', 'SUB.JUMP.TenBridge'], ['hour-boundary']),
  node('TIME.CALC.Elapsed', [TG], 'time-calc', 'Hoe lang duurt het?',
    'Ik kan de duur berekenen via het hele uur, ook de volgende dag.',
    'Finds duration by bridging to the next hour; handles an explicit next day.',
    ['TIME.CALC.Offset', 'REL.ADD.Inverse'], ['hour-boundary', 'next-day']),
  node('TIME.SCHEDULE.SelectInterval', [TG], 'time-schedule', 'Dienstregeling lezen',
    'Ik kan de goede rijen kiezen in een dienstregeling en dan rekenen.',
    'Selects relevant departure/arrival rows before calculating duration.',
    ['TIME.CALC.Elapsed', 'META.EQUATION.Select'], ['irrelevant-row']),
  node('CAL.UNIT.MonthQuarterYear', [TG], 'calendar', 'Maanden, kwartalen, jaren',
    'Ik weet hoe maanden, kwartalen, weken en jaren bij elkaar horen.',
    'Relates months/quarters/years; distinguishes exact and approximate week counts.',
    ['FND.COUNT.Group'], []),
  node('CAL.DATE.MonthLength', [TG], 'calendar', 'Dagen in een maand',
    'Ik weet hoeveel dagen een maand heeft, ook februari als het getoond wordt.',
    'Uses an explicit year’s month lengths, including February when shown.',
    ['CAL.UNIT.MonthQuarterYear'], ['month-boundary']),
  node('CAL.DATE.Navigate', [TG], 'calendar', 'Datums doorrekenen',
    'Ik kan dagen en weekdagen doorrekenen over de maandgrens.',
    'Moves dates/weekdays across month and year boundaries.',
    ['CAL.DATE.MonthLength', 'FND.FACT.AddWithin20', 'FND.FACT.SubWithin20'], ['month-boundary', 'year-boundary']),
  node('MONEY.VALUE.Denomination', [TG], 'money', 'Munten en biljetten',
    'Ik ken de waarde van munten en biljetten, los van hun grootte.',
    'Recognizes coin/note value independent of physical size or quantity.',
    ['PV.DHTE.Compose'], []),
  node('MONEY.NOTATION.EuroCent', [TG], 'money', 'Euro’s en centen schrijven',
    'Ik kan 475 cent schrijven als €4,75, met twee cent-plekken.',
    'Connects 475 cent and €4,75; preserves the two cent places.',
    ['MONEY.VALUE.Denomination', 'PV.SCALE.TenHundred'], ['comma-format', 'leading-zero']),
  node('MONEY.PAY.Exact', [TG], 'money', 'Gepast betalen',
    'Ik kan een bedrag precies maken met munten en biljetten en controleren.',
    'Builds and verifies an exact amount using available denominations.',
    ['MONEY.NOTATION.EuroCent', 'ADD.JUMP.TenBridge'], []),
  node('MONEY.PAY.Minimal', [TG], 'money', 'Zo weinig mogelijk munten',
    'Ik kan hetzelfde bedrag betalen met zo weinig mogelijk munten.',
    'Exchanges equal-value collections to minimize item count under stated availability.',
    ['MONEY.PAY.Exact'], ['equality-first']),
  node('MONEY.CALC.Add', [TG], 'money', 'Geld optellen',
    'Ik kan bedragen optellen en 100 cent omwisselen voor een euro.',
    'Adds amounts with cent-to-euro regrouping.',
    ['MONEY.NOTATION.EuroCent', 'ADD.COLUMN.Carry'], ['cent-regroup']),
  node('MONEY.CALC.Subtract', [TG], 'money', 'Geld aftrekken',
    'Ik kan bedragen aftrekken en een euro omwisselen voor centen.',
    'Subtracts amounts with euro-to-cent regrouping.',
    ['MONEY.NOTATION.EuroCent', 'SUB.COLUMN.BorrowCrossout'], ['euro-regroup']),
  node('MONEY.CHANGE.Complement', [TG], 'money', 'Wisselgeld terugrekenen',
    'Ik kan van prijs naar betaald bedrag terugtellen en het controleren.',
    'Counts up from price to payment and verifies price + change = paid.',
    ['MONEY.PAY.Exact', 'REL.ADD.MissingPart'], ['inverse-verification']),
  node('MONEY.CONTEXT.DiscountShortfall', [TG], 'money-context', 'Korting en tekort',
    'Ik kan prijs, korting, tekort en wisselgeld uit elkaar houden.',
    'Distinguishes price, discount, amount available, shortfall, and change.',
    ['MONEY.CALC.Subtract', 'META.EQUATION.Select', 'META.ANSWER.Unit'], []),
]

export const SKILL_INDEX: ReadonlyMap<SkillId, KnowledgeGraphNode> = new Map(
  KNOWLEDGE_GRAPH.map((n) => [n.id, n]),
)

export function getSkill(skillId: SkillId): KnowledgeGraphNode {
  const node = SKILL_INDEX.get(skillId)
  if (!node) throw new Error(`Unknown skill: ${skillId}`)
  return node
}

export function prerequisiteEdges(): Array<{ from: SkillId; to: SkillId }> {
  const edges: Array<{ from: SkillId; to: SkillId }> = []
  for (const n of KNOWLEDGE_GRAPH) {
    for (const p of n.prerequisites) edges.push({ from: p, to: n.id })
  }
  return edges
}

export function descendants(skillId: SkillId): SkillId[] {
  const direct = KNOWLEDGE_GRAPH.filter((n) => n.prerequisites.includes(skillId))
  return direct.map((n) => n.id)
}

export const THEME_META: Record<ThemeId, { titleNl: string; emoji: string }> = {
  'optellen-aftrekken': { titleNl: 'Optellen & aftrekken', emoji: '➕' },
  meten: { titleNl: 'Meten', emoji: '📏' },
  'vermenigvuldigen-delen': { titleNl: 'Vermenigvuldigen & delen', emoji: '✖️' },
  'tijd-geld': { titleNl: 'Tijd en geld', emoji: '🕐' },
}